### PR TITLE
Add support for validating IPv4/IPV6 address

### PR DESCRIPTION
**Pull request by abelbeck**
Add support for validating IPv4/IPV6 address, Issue #5

### CODE REVIEW

**Comment by troglobit** [comment]
Looks good.  We just need to figure out what to call these new options, `-c` for disabling color and `-C` to check the address .... what can we do here? :confused: 

FYI, you don't need braces for one-liner `if()` statements :smiley:

**Comment by troglobit** [comment]
How about we use `-n` for "No color in output", and `-c` to check the IP address?  It's a bit cleaner. I can fix it later if you don't have a better suggestion for a short-option replacement.

**Comment by abelbeck** [comment]
Possibly -n for "no color" and use -c for check/validate (as some ipcalc's do).

Also, can we tell if the output is not a terminal (pipe or redirection) and automatically disable coloring ?

> FYI, you don't need braces for one-liner if() statements 😃

Yes, I like to always use braces regardless, as a style.

**Comment by troglobit** [comment]
Heh, great minds ;)

Maybe `isatty(1)` could help?

Ah, well that's a good practise in general, but in most projects it's better to fit in with the existing code. No matter, I can clean that up later.

**Comment by abelbeck** [comment]
> Heh, great minds ;)

indeed. :-)

I can make the -n / -c change in my PR in an hour or so, if you don't beat me to it.

**Comment by troglobit** [comment]
Great, please do!  (I'm off to bed some kids anyway)

**Pull request merged**
